{
    'name': 'Custom Invoice Calculation',
    'version': '18.0.4.0.0',
    'summary': 'Custom calculation for invoice lines with selectable total methods',
    'depends': ['account', 'product', 'sale_usd_to_bdt'],
    'data': [
        'security/ir.model.access.csv',
        'data/charge_product.xml',
        'data/total_types.xml',
        'report/report_invoice.xml',
        'report/report_invoice_split_table.xml',
        'report/report_invoice_table.xml',
        'views/product_template_views.xml',
        'views/account_move_line_views.xml',
        'views/account_move_views.xml',
        'views/account_move_line.xml',
    ],
    'installable': True,
    'auto_install': False,
}